export const eventsConfig = [
    {
        id: 44,
        eventDay: 'ПН',
        eventDayNumber: '13',
        eventInfoDate: 'с 13 по 19 марта',
        eventInfoTitle: 'Весенняя выставка "Надежда"',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'с 13 по 19 марта в ДК "Звездный" пройдет выставка "Надежда" в клубе равных возможностей.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/nadejda-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/nadejda-02.jpg'),
    },
    {
        id: 43,
        eventDay: 'ВС',
        eventDayNumber: '12',
        eventInfoDate: '12 марта',
        eventInfoTitle: 'Открытый фестиваль народного творчества',
        eventPlace: 'ДК Звёздный',
        eventDescription: '12 марта в ДК "Звездный" в 13:00 состоится шестой открытый фестиваль народного творчества "Семёновна", посвященный памяти Валентины Семёновны Решетниковой.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/semenovna2023-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/semenovna2023-02.jpg'),
    },
    {
        id: 42,
        eventDay: 'ВС',
        eventDayNumber: '5',
        eventInfoDate: '5 марта',
        eventInfoTitle: 'Концерт для милых дам',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'Приглашаем на концерт для милых дам, девочек и девушек, женщин и бабушек, - для всех представительниц прекрасной половины человечества 5 марта в 13 часов в ДК "Юбилейный" состоится концерт "ЛЮБИМЫМ, НЕЖНЫМ И ПРЕКРАСНЫМ". Солисты творческих коллективов из разных структурных подразделений ДК "Звёздный" представят свои новые и самые яркие постановки к Международному женскому дню!',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/8march-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/8march-02.jpg'),
    },
    {
        id: 41,
        eventDay: 'ВС',
        eventDayNumber: '5',
        eventInfoDate: '5 марта',
        eventInfoTitle: 'Пижамная вечеринка',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'Только для девочек и только в пижамах к Международному женскому дню 5 марта в 17 часов в ДК "Звёздный" состоится незабываемая встреча в необычном формате. Режиссёр массовых мероприятий Мадина Романчева приглашает девочек на пижамную вечеринку.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/party-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/party-02.jpg'),
    },
    {
        id: 40,
        eventDay: 'СБ',
        eventDayNumber: '4',
        eventInfoDate: '4 марта',
        eventInfoTitle: 'Концерт группы "Shizgarin"',
        eventPlace: 'ДК Звёздный',
        eventDescription: '4 марта в ДК "Звездный" состоится концерт группы "Shizgarin". Сбор гостей в 17:00. Будет организованы фуршет, фото зона, лотерея. Пройдет выставка и продажа косметических средств, ароматических свечей, флористических композиций. ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/shizgarin-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/shizgarin-02.jpg'),
    },
    {
        id: 39,
        eventDay: 'ПТ',
        eventDayNumber: '3',
        eventInfoDate: '3 марта',
        eventInfoTitle: 'Вечер-встреча к Международному женскому дню',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'К международному женскому дню 3 марта в 18 часов в доме культуры "Звёздный" состоится творческая встреча с Александром Шагановым. Российский поэт-песенник, автор текстов многих хитов отечественной эстрады выступит для жителей Новой Москвы.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/vstre4a-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/vstre4a-02.jpg'),
    },
    {
        id: 38,
        eventDay: 'СР',
        eventDayNumber: '1',
        eventInfoDate: '1 марта',
        eventInfoTitle: 'Всемирный день кошек',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'Пушистый друг 1 марта ко Всемирному дню кошек в социальных сетях ДК "Звёздный" пройдёт онлайн выставка. Солисты творческого коллектива делятся фотографиями своих любимых питомцев. А у вас живут дома "усатые и полосатые"? Ждём фотографии ваших пушистых друзей в комментариях!',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/kis-kis-0111.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kis-kis-2-02.jpg'),
    },
    {
        id: 37,
        eventDay: 'СР',
        eventDayNumber: '1',
        eventInfoDate: 'c 1 марта по 9 апреля',
        eventInfoTitle: 'Мероприятия библиотеки Былово',
        eventPlace: 'Библиотека Былово',
        eventDescription: 'С 1 марта по 9 апреля в библиотеке "Былово" пройдёт серия мероприятий: "Гуляют кошки по страницам", "О, женщина, краса земная!", "Голубая планета в руках человека", "Растим читателя вместе".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/mar-byl-lib-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/mar-byl-lib-02.jpg'),
    },
    {
        id: 36,
        eventDay: 'СР',
        eventDayNumber: '1',
        eventInfoDate: 'c 3 по 31 марта',
        eventInfoTitle: 'Мероприятия библиотеки Минзаг',
        eventPlace: 'Библиотека Минзаг',
        eventDescription: 'С 3 по 31 марта в библиотеке "Минзаг" пройдёт серия мероприятий: "Выставка рукоделия", "Яркие женщины - яркие судьбы", "Михалкова знают все", "Будь человеком!", "Красочный мир".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/library-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/library-02.jpg'),
    },

    {
        id: 35,
        eventDay: 'СР',
        eventDayNumber: '1',
        eventInfoDate: 'c 1 марта по 8 апреля',
        eventInfoTitle: 'Мероприятия Краснопахорской библиотеки',
        eventPlace: 'Библиотека Красная Пахра',
        eventDescription: 'С 1 марта по 8 апреля в библиотеке "Красная Пахра" пройдёт серия мероприятий: "Гений живописи Серебрянного века", "Красота спасет мир", "Наши мамы дорогие", "Мир детства С. Михалкова", "И в каждый строчке вдохновенье", "За чудесами на морское дно", "За горьковской строкой", "Добрый мир любимых книг".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/library-kr-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/library-kr-02.jpg'),
    },
    {
        id: 34,
        eventDay: 'СБ',
        eventDayNumber: '26',
        eventInfoDate: '26 февраля',
        eventInfoTitle: 'Мероприятие "Масленичные забавы"',
        eventPlace: 'ДК Звёздный',
        eventDescription: '26 февраля в 13:00 в ДК "Звездный" состоится празднество, посвященное дню "Масленичные забавы".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/maslo-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/maslo-02.jpg'),
    },
    {
        id: 33,
        eventDay: 'СБ',
        eventDayNumber: '25',
        eventInfoDate: '25 февраля',
        eventInfoTitle: 'Мероприятие "Широкая масленица"',
        eventPlace: 'ДК Юбилейный',
        eventDescription: '25 февраля в 12:00 в ДК "Юбилейный" состоится празднество, посвященное дню "Широкая масленица".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/maslo-dk-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/maslo-dk-02.jpg'),
    },
    {
        id: 32,
        eventDay: 'ВС',
        eventDayNumber: '19',
        eventInfoDate: 'c 19 по 26 февраля',
        eventInfoTitle: 'Выставка работ',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'с 19 по 26 февраля пройдет выставка Владимира Савельева, посвящённая "Дню защитника Отечества"',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/saveliev-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/saveliev-02.jpg'),
    },
    {
        id: 31,
        eventDay: 'ВТ',
        eventDayNumber: '28',
        eventInfoDate: '28 февраля',
        eventInfoTitle: 'Выставка "Моя Страна - Моя Россия"',
        eventPlace: 'ДК Звёздный',
        eventDescription: '28 февраля состоится круглый стол с участием клубных формирований, направленный на стабилизацию межнациональных и межконфессиональных отношений.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/mejetnos-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/mejetnos-02.jpg'),
    },
    {
        id: 30,
        eventDay: 'ПН',
        eventDayNumber: '27',
        eventInfoDate: 'c 27 февраля по 3 марта',
        eventInfoTitle: 'Выставка детского творчества',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'С 27 февраля по 3 марта в ДК "Юбилейный" пройдет выставка детского творчества, посвящённая "Дню защитника Отечества".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/vistavka-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/vistavka-02.jpg'),
    },
    {
        id: 29,
        eventDay: 'ЧТ',
        eventDayNumber: '23',
        eventInfoDate: '23 февраля',
        eventInfoTitle: 'Цирковое представление "Щенячий патруль"',
        eventPlace: 'ДК Звёздный',
        eventDescription: 'ЦИРК! ЦИРК! ЦИРК! 23 февраля в 12 часов в ДК "Звёздный" состоится цирковое представление. В программе: выступления артистов и клоунов, фокусы и бумажное шоу. Стоимость билетов: 700 рублей',
        eventCost: 'Платно',
        eventImgSrc: require('../../assets/images/eventsImages/paw-patrol-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/paw-patrol-02.jpg'),
    },
    {
        id: 28,
        eventDay: 'ВТ',
        eventDayNumber: '22',
        eventInfoDate: '22 февраля',
        eventInfoTitle: 'Открытиый урок "Золотые Голоса"',
        eventPlace: 'ДК Звёздный',
        eventDescription: '22 февраля в 16:00 состоится открытиый урок в студии эстрадного вокала "Золотые Голоса"',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/golosa-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/golosa-02.jpg'),
    },
    {
        id: 27,
        eventDay: 'ПН',
        eventDayNumber: '20',
        eventInfoDate: 'c 20 по 26 февраля',
        eventInfoTitle: 'выставка детских работ "Арт студии"',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'С 20 по 26 февраля в ДК "Юбилейный" пройдет творческая выставка детских работ "Арт студии".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/art-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/art-02.jpg'),
    },
]